workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
      when: never
    - when: always

branch:
  stage: test
  trigger:
    include:
      - local: ci/branch.yaml
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH

release:
  stage: build
  trigger:
    include:
      - local: ci/release.yaml
    strategy: depend
  rules:
    - if: $CI_COMMIT_TAG
