include:
  - project: 'just-ci/templates'
    file: 'templates/container/python.yml'
    ref: 'v5.0.0-beta.9'
  - project: 'just-ci/templates'
    file: 'project-automation/badge.yml'

variables:
  PYTHON_PACKAGE: 'dgad'
  KANIKO_EXTRA_ARGS: "--use-new-run --single-snapshot"

dgad-cli:
  stage: test
  script:
    - which dgad
    - dgad --domain wikipedia.org
    - dgad --domains wikipedia.org sjdkahflaksdjhf.net
    - dgad --csv tests/data/domains_todo.csv

kaniko:redis-worker:
  extends: .kaniko
  variables:
    KANIKO_REGISTRY_IMAGE: ${CI_REGISTRY_IMAGE}/redis-worker
    KANIKO_CONTEXT: ${CI_PROJECT_DIR}/redis-worker
    KANIKO_DOCKERFILE: ${CI_PROJECT_DIR}/redis-worker/Dockerfile

# FIXME
python:mypy:
  allow_failure: true

# TODO: move to just-ci/templates
python:twine:pypi:
  image: registry.gitlab.com/just-ci/images/python:3.9
  stage: .post
  before_script:
    - cat $pypirc > .pypirc
  script:
    - pip3 install twine build
    - python3 -m build
    - twine upload --skip-existing --config-file .pypirc dist/*
  rules:
    - if: ($CI_COMMIT_TAG =~ /^v[0-9]+(\.[0-9]+){2}(.*)$/)

# badges

prepare:badges:
  stage: .pre
  image:
    name: alpine/git
    entrypoint: [""]
  script:
    - echo "COMMITS_COUNT=$(git rev-list --all --count)" >> badges.env
    - echo "LATEST_TAG=$(git tag | sort -g | tail -1)" >> badges.env
  artifacts:
    reports:
      dotenv: badges.env

.badge:
  dependencies:
    - prepare:badges

badge:commits:
  extends: .badge
  variables:
    LABEL: "commits"
    VALUE: "${COMMITS_COUNT}"
    COLOR: "green"
    URL: "${CI_PROJECT_URL}"

badge:version:
  extends: .badge
  variables:
    LABEL: "version"
    VALUE: "${LATEST_TAG}"
    COLOR: "blue"
    URL: "${CI_PROJECT_URL}"
