fail_fast: true
default_stages: [commit]
repos:
-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.2.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: detect-private-key
-   repo: local
    hooks:
    -   id: system
        name: Black
        entry: poetry run black --check .
        pass_filenames: false
        language: system
-   repo: local
    hooks:
    -   id: system
        name: isort
        entry: poetry run isort --profile=black --check .
        pass_filenames: false
        language: system
-   repo: local
    hooks:
    -   id: system
        name: safety
        entry: poetry run safety check
        pass_filenames: false
        language: system
-   repo: local
    hooks:
    -   id: system
        name: bandit
        entry: poetry run bandit -r dgad
        pass_filenames: false
        language: system
-   repo: local
    hooks:
    -   id: system
        name: mypy
        entry: poetry run mypy --strict --pretty --ignore-missing-imports dgad
        pass_filenames: false
        language: system
-   repo: local
    hooks:
    -   id: system
        name: pylint
        entry: poetry run pylint --fail-under 7.0 dgad
        pass_filenames: false
        language: system
-   repo: local
    hooks:
    -   id: system
        name: pytest
        entry: poetry run pytest -n 6 --cov=dgad tests
        pass_filenames: false
        language: system
-   repo: local
    hooks:
    -   id: system
        name: test_cli
        entry: poetry run python dgad/app/cli.py --domain=google.com
        language: system
        pass_filenames: false
