apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: dgad
build:
  artifacts:
  - image: registry.gitlab.com/cossas/dgad:v3.1.2
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - skaffold/deployment.yaml
    - skaffold/svc-clusterIP.yaml
