# type: ignore

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dgad.grpc.classification_pb2 as classification__pb2


class ClassifierStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetClassification = channel.unary_unary(
            "/Classifier/GetClassification",
            request_serializer=classification__pb2.Domain.SerializeToString,
            response_deserializer=classification__pb2.Classification.FromString,
        )


class ClassifierServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetClassification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ClassifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetClassification": grpc.unary_unary_rpc_method_handler(
            servicer.GetClassification,
            request_deserializer=classification__pb2.Domain.FromString,
            response_serializer=classification__pb2.Classification.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "Classifier", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Classifier(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetClassification(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/Classifier/GetClassification",
            classification__pb2.Domain.SerializeToString,
            classification__pb2.Classification.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
