# type: ignore

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classification.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="classification.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x14\x63lassification.proto"\x16\n\x06\x44omain\x12\x0c\n\x04\x66qdn\x18\x01 \x01(\t"=\n\x0e\x43lassification\x12\x0c\n\x04\x66qdn\x18\x01 \x01(\t\x12\x1d\n\x15\x62inary_classification\x18\x02 \x01(\t2=\n\nClassifier\x12/\n\x11GetClassification\x12\x07.Domain\x1a\x0f.Classification"\x00\x62\x06proto3',
)


_DOMAIN = _descriptor.Descriptor(
    name="Domain",
    full_name="Domain",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="fqdn",
            full_name="Domain.fqdn",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=24,
    serialized_end=46,
)


_CLASSIFICATION = _descriptor.Descriptor(
    name="Classification",
    full_name="Classification",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="fqdn",
            full_name="Classification.fqdn",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="binary_classification",
            full_name="Classification.binary_classification",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=48,
    serialized_end=109,
)

DESCRIPTOR.message_types_by_name["Domain"] = _DOMAIN
DESCRIPTOR.message_types_by_name["Classification"] = _CLASSIFICATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Domain = _reflection.GeneratedProtocolMessageType(
    "Domain",
    (_message.Message,),
    {
        "DESCRIPTOR": _DOMAIN,
        "__module__": "classification_pb2"
        # @@protoc_insertion_point(class_scope:Domain)
    },
)
_sym_db.RegisterMessage(Domain)

Classification = _reflection.GeneratedProtocolMessageType(
    "Classification",
    (_message.Message,),
    {
        "DESCRIPTOR": _CLASSIFICATION,
        "__module__": "classification_pb2"
        # @@protoc_insertion_point(class_scope:Classification)
    },
)
_sym_db.RegisterMessage(Classification)


_CLASSIFIER = _descriptor.ServiceDescriptor(
    name="Classifier",
    full_name="Classifier",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=111,
    serialized_end=172,
    methods=[
        _descriptor.MethodDescriptor(
            name="GetClassification",
            full_name="Classifier.GetClassification",
            index=0,
            containing_service=None,
            input_type=_DOMAIN,
            output_type=_CLASSIFICATION,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_CLASSIFIER)

DESCRIPTOR.services_by_name["Classifier"] = _CLASSIFIER

# @@protoc_insertion_point(module_scope)
