services:
    grpc_detective:
        image: registry.gitlab.com/cossas/dgad:v4.1.1
        entrypoint: ""
        command: python dgad/grpc/classifier_server.py
        deploy:
            replicas: 1
        env_file:
            - config.env
        restart: always

    redis_worker:
        image: registry.gitlab.com/cossas/dgad/redis_worker:v4.1.1
        env_file:
            - config.env
        environment:
            DGAD_GRPC_HOST: grpc_detective
        deploy:
            replicas: 1
        restart: always
